#!/usr/bin/env node
/**
 * Generates Subresource-Integrity hashes for every CDN URL listed in js/core/loader.js (MT.libs)
 * and writes them to js/core/sri.js. Run on any machine with internet access:
 *
 *     node tools/gen-sri.mjs
 *
 * Re-run whenever you change a library version. URLs that fail to download are skipped (they simply load without SRI).
 */
import fs from 'node:fs';
import vm from 'node:vm';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sandbox = { window: { MT: {} }, document: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, 'js/core/loader.js'), 'utf8'), sandbox);
const libs = sandbox.window.MT.libs;
const urls = new Set();
for (const def of Object.values(libs)) {
  (def.js || []).forEach((u) => urls.add(u));
  (def.css || []).forEach((alts) => alts.forEach((u) => urls.add(u)));
}
const out = {};
for (const url of urls) {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error('HTTP ' + res.status);
    const buf = Buffer.from(await res.arrayBuffer());
    out[url] = 'sha384-' + crypto.createHash('sha384').update(buf).digest('base64');
    console.log('ok  ', url);
  } catch (e) { console.warn('skip', url, '-', e.message); }
}
const body = '/* Generated by tools/gen-sri.mjs — do not edit by hand. */\n(window.MT = window.MT || {}).sri = ' + JSON.stringify(out, null, 2) + ';\n';
fs.writeFileSync(path.join(root, 'js/core/sri.js'), body);
console.log(`\nWrote js/core/sri.js with ${Object.keys(out).length} hashes.`);
